networks:
  default:
    driver: bridge

services:
  postgres:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    restart: always
    environment: 
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "Exchange"
    networks:
      - default
    
  liquibase:
    image: liquibase/liquibase:4.6.1
    volumes:
      - ./migrations:/liquibase/changelog
    command: "--changelog-file=changelog.xml --classpath=./changelog --defaultsFile=./changelog/dev.properties --password=postgres update"
    depends_on:
      - postgres
    networks:
      - default
        
  exchange:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/app
    depends_on:
      - liquibase
    networks:
      - default