networks:
  default:
    driver: bridge

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.Pg
    ports:
      - "5432:5432"
    restart: always
    environment: 
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "Exchange"
    networks:
      - default
    
  liquibase:
    build:
      context: .
      dockerfile: Dockerfile.Lb
    depends_on:
      - postgres
    networks:
      - default
        
  exchange:
#    image: tochka-exchange-exchange:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/app
    depends_on:
      - postgres
    networks:
      - default
